/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Usuario;
import Service.ServiceUser;
import java.sql.SQLException;
import javax.swing.JComponent;

/**
 *
 * @author naxch
 */
public class Login extends javax.swing.JPanel {
    
    private ServiceUser su;
    PanelPrincipal panelPrincipal;
    MainPanel mainPanel;
    
    private Usuario user;
    private String email;
    private String pass;
    
    public Login(PanelPrincipal panel) {
        initComponents();
        panelPrincipal = panel;
    }
    
    private void iniciarSesion() throws SQLException{
        email = etUser.getText();
        pass = etPassword.getText();
        if(email.length()>0 && pass.length()>0){
            su = new ServiceUser();
            
            Usuario usuario = new Usuario();
            usuario.setEmail(email);
            usuario.setPassword(pass);
            
            if(!(su.login(usuario) == null)){
                user = su.login(usuario);
                System.out.println("Bienvenido "+user.getNombre());
            }else{
                System.out.println("Usuario no encontrado");
            }
        }
        mainPanel = new MainPanel();
<<<<<<< HEAD:estacionamiento/Estacionamiento/src/Vista/Login.java
        mainPanel.setSize(1500, 1200);
=======
        mainPanel.setSize(600, 600);
>>>>>>> 80c7468859780394946009343709dd21addffa9b:Estacionamiento/src/Vista/Login.java
        mainPanel.setLocation(0, 0);
        
        panelPrincipal.vistaPrograma(mainPanel);
    }
    
    public Usuario getUser(){
        return this.user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        etPassword = new javax.swing.JPasswordField();

<<<<<<< HEAD:estacionamiento/Estacionamiento/src/Vista/Login.java
        setToolTipText("center");
        setMaximumSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(136, 232, 242));
        jPanel1.setForeground(new java.awt.Color(137, 194, 217));
        jPanel1.setToolTipText("center");
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
=======
        jPanel1.setBackground(new java.awt.Color(136, 232, 242));
        jPanel1.setForeground(new java.awt.Color(137, 194, 217));
>>>>>>> 80c7468859780394946009343709dd21addffa9b:Estacionamiento/src/Vista/Login.java

        jLabel1.setBackground(new java.awt.Color(242, 242, 24));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio Sesion");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        etUser.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        etUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña");

        btnIniciarSesion.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnIniciarSesion.setText("Entrar");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        etPassword.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        etPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnIniciarSesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etUser, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(etPassword))))
<<<<<<< HEAD:estacionamiento/Estacionamiento/src/Vista/Login.java
                .addContainerGap(24, Short.MAX_VALUE))
=======
                .addContainerGap(25, Short.MAX_VALUE))
>>>>>>> 80c7468859780394946009343709dd21addffa9b:Estacionamiento/src/Vista/Login.java
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etUser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(etPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD:estacionamiento/Estacionamiento/src/Vista/Login.java
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
>>>>>>> 80c7468859780394946009343709dd21addffa9b:Estacionamiento/src/Vista/Login.java
                .addComponent(btnIniciarSesion)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD:estacionamiento/Estacionamiento/src/Vista/Login.java
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
>>>>>>> 80c7468859780394946009343709dd21addffa9b:Estacionamiento/src/Vista/Login.java
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        try {
            // TODO add your handling code here:
            iniciarSesion();
        } catch (SQLException ex) {
            System.out.println("Error en boton login\n---> "+ex);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPasswordField etPassword;
    private javax.swing.JTextField etUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
